services:
  - type: web
    name: reserva-api
    runtime: php
    repo: https://github.com/gerry404/reserva
    rootDir: backend
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: Réserva
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_WEBHOOK_HASH
        sync: false
      - key: MAIL_MAILER
        value: log
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
